### ISSUE TITLE
Tensor flow error when starting up the flask server

### ISSUE THREAD

**Issue by Arvind6353** [adeshpande3/Chatbot-Flask-Server#1]
Getting the below error when starting up the server:.
Please help

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [223,48
] rhs shape= [223,112]

[[Node: save/Assign_7 = Assign[T=DT_FLOAT, _class=["loc:@embedding_rnn_seq2seq/rnn/embedding_wrapper/embed
ding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_rn
n_seq2seq/rnn/embedding_wrapper/embedding, save/RestoreV2_7)]]

**Comment by adeshpande3** [comment]
See https://github.com/adeshpande3/Facebook-Messenger-Bot/issues/9

**Comment by Arvind6353** [comment]
Hi ,

After I ran the Seq2Seq.py i got the checklist and files and i added those
to the flask server models folder.
When i ran the app. Am getting empty responses for whatever data I input.

ids are coming as the following when I enter any text.
[[33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]
 [33595]]

Can you help me with this ?


Thanks,
Arvind

**Comment by adeshpande3** [comment]
You need to make sure you've trained the model for long enough. Lines 212-238 should train the model as well as show you what how the network responds to sample test screens.

**Comment by Fleker** [comment]
As an addendum, I had a similar problem that I had to solve by working backwards.

`InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [192] rhs shape= [448]`

My LHS count was defined as `48`, making the LHS side 192 by a multiplier of 4. To get it to match the RHS, I changed the count to `112`. That resolved the error.
