### ISSUE TITLE
The method is not allowed for the requested URL

### ISSUE THREAD

**Issue by tap222** [adeshpande3/Chatbot-Flask-Server#5]
E HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
405 Method Not Allowed</title>
Method Not Allowed</h1>
The method is not allowed for the requested URL.</p>
Getting this error message when I am input any message into facebook messenger bot.

**Comment by adeshpande3** [comment]
Are you sure it's a problem with the Flask server? It seems like it might be an issue with how you've set up the express server, in which case you should look [here](https://github.com/jw84/messenger-bot-tutorial/issues) for issues.

**Comment by tap222** [comment]
Yeah,I have double checked and I have followed as per your instruction.
Here my heroku https://mighty-dusk-78515.herokuapp.com/
you can check it.

**Comment by adeshpande3** [comment]
Seems to be working for me.

**Comment by tap222** [comment]
I have tweaked some code in app.py because it was throwing some error.

```
app = Flask(__name__, template_folder='./')
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/prediction', methods=['GET','POST'])
def prediction():
    if request.form != None and 'message' in request.form:
        msg = request.form['message']
        response =  pred(str(msg))
        return jsonify(response) 
    else:
        return render_template('index.html')
      
if __name__ == '__main__':
    app.debug = True
    app.run()

```
and accordingly I have changed in index.js.

```

const myID = 1960455644201170;

app.post('/webhook/', function (req, res) {
    let messaging_events = req.body.entry[0].messaging
    for (let i = 0; i < messaging_events.length; i++) {
	    let event = req.body.entry[0].messaging[i]
	    let sender = event.sender.id

	    if (event.message && event.message.text && sender != myID) {
	    	let text = event.message.text
			request({
			    url= 'https://mighty-dusk-78515.herokuapp.com/',
			    method: 'POST',
			    body: {message: text.substring(0, 200)},
			    headers: {'User-Agent': 'request'},
				json: true 
			}, function(error, response, body) {
				sendTextMessage(sender, response.body)
			})
	    }
    }
    res.sendStatus(200)
})


```

Also,index.html code
```
<form action="{{ url_for('prediction') }}" method='POST' >
    <input type="text" value="" placeholder="Enter your Message" name="message" id="message">
    <input type="submit" value="submit" >
```

**Comment by tap222** [comment]
Issue resolved

**Comment by venkatraju25** [comment]
import numpy as np
import pandas as pd
from flask import Flask,request,render_template,jsonify
import joblib
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.simplefilter(action='ignore', category=UserWarning)


app=Flask(__name__)

churnlog=joblib.load(open('churnlog.pkl','rb'))


@app.route('/',methods=['GET'])
def home():
    return render_template('index.html')




@app.route('/predict',methods=[ 'GET' ,'POST'])    
def predict():
     
    
    
    
     features=[]
     features.append(request.form.get('gender'))
     features.append(request.form.get('SeniorCitizen'))
     features.append(request.form.get('Partner'))
     
     features.append(request.form.get('Dependents'))
     features.append(request.form.get('tenure'))
     features.append(request.form.get('PhoneService'))
     
     features.append(request.form.get('MultipleLines'))
     features.append(request.form.get('InternetService'))
     features.append(request.form.get('OnlineSecurity'))
     
     features.append(request.form.get('OnlineBackup'))
     features.append(request.form.get('DeviceProtection'))
     features.append(request.form.get('TechSupport'))
     
     features.append(request.form.get('StreamingTV'))
     features.append(request.form.get('StreamingMovies'))
     features.append(request.form.get('Contract'))
     
     features.append(request.form.get('PaperlessBilling'))
     features.append(request.form.get('PaymentMethod'))
     
     features.append(request.form.get('MonthlyCharges'))
     features.append(request.form.get('TotalCharges'))
  
        
     #input_features = [int(x) for x in request.form.values()]
     #final_features=[np.array(features)]
     prediction=churnlog.predict(features)
     #features.append(input_features)
    
    
                      
#     prediction = churnlog.predict(features)
        
     if prediction == 0:
         res_val = "NOT A CHURN CUSTOMER"
     else:
         res_val = "CHURN CUSTOMER"
        
     return render_template('index.html',prediction_text='The churn of the customer is {}'.format(res_val))


if __name__=="__main__":
    app.run(debug=True,use_reloader=False)

**Comment by venkatraju25** [comment]
I am getting method is not allowed can u suggest me a solution
